// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfvlxokargdcbpkizjfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmdmx4b2thcmdkY2Jwa2l6amZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgwNTI1NjksImV4cCI6MjA4MzYyODU2OX0.L-VHS_PkST0Qlkcz3JBZT5kuTiFQts_TDp23_BNVfQw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});