// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncqrserzcruadqtxgjvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jcXJzZXJ6Y3J1YWRxdHhnanZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMzkxNDAsImV4cCI6MjA2OTgxNTE0MH0.u_TLQ8aEehjwuoFOPbnLhF0UI6L6vkRKHJGdBc8_MpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});